apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: citibike-train
  namespace: citibike
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/mpgregor/airkube:latest
              imagePullPolicy: Always
              command:
                - "python"
                - "/pipeline/load_train.py"
                - "--account="
                - "--password="
